// Mock data for development when database is not available
import type { Project, Employee, Department, ContractType, Invoice } from '@shared/api';

export const mockDepartments: Department[] = [
  { id: 1, name: 'Production', description: 'Équipe de production audiovisuelle', employee_count: 3, created_at: '2023-01-01', updated_at: '2023-01-01' },
  { id: 2, name: 'Technique', description: 'Équipe technique et matériel', employee_count: 2, created_at: '2023-01-01', updated_at: '2023-01-01' },
  { id: 3, name: 'Post-Production', description: 'Montage et finalisation', employee_count: 1, created_at: '2023-01-01', updated_at: '2023-01-01' },
  { id: 4, name: 'Direction', description: 'Direction et management', employee_count: 1, created_at: '2023-01-01', updated_at: '2023-01-01' },
];

export const mockContractTypes: ContractType[] = [
  { id: 1, name: 'CDI', is_permanent: true, description: 'Contrat à Durée Indéterminée', created_at: '2023-01-01', updated_at: '2023-01-01' },
  { id: 2, name: 'CDD', is_permanent: false, description: 'Contrat à Durée Déterminée', created_at: '2023-01-01', updated_at: '2023-01-01' },
  { id: 3, name: 'Freelance', is_permanent: false, description: 'Travailleur indépendant', created_at: '2023-01-01', updated_at: '2023-01-01' },
  { id: 4, name: 'Stage', is_permanent: false, description: 'Stage étudiant', created_at: '2023-01-01', updated_at: '2023-01-01' },
];

export const mockEmployees: Employee[] = [
  {
    id: 1,
    first_name: 'Alice',
    last_name: 'Martin',
    email: 'alice.martin@nomedia.ma',
    phone: '+212 6 12 34 56 78',
    address: 'Casablanca, Maroc',
    position: 'Réalisatrice',
    department_id: 1,
    department_name: 'Production',
    salary: 45000,
    hire_date: '2023-01-15',
    status: 'active',
    created_at: '2023-01-15',
    updated_at: '2023-01-15',
    contract_type: 'CDI',
    contract_start_date: '2023-01-15',
    contract_status: 'active',
    active_projects: 2,
  },
  {
    id: 2,
    first_name: 'Bob',
    last_name: 'Dupont',
    email: 'bob.dupont@nomedia.ma',
    phone: '+212 6 23 45 67 89',
    address: 'Rabat, Maroc',
    position: 'Cameraman',
    department_id: 2,
    department_name: 'Technique',
    salary: 35000,
    hire_date: '2023-03-20',
    status: 'active',
    created_at: '2023-03-20',
    updated_at: '2023-03-20',
    contract_type: 'CDI',
    contract_start_date: '2023-03-20',
    contract_status: 'active',
    active_projects: 1,
  },
  {
    id: 3,
    first_name: 'Carol',
    last_name: 'Leroy',
    email: 'carol.leroy@nomedia.ma',
    phone: '+212 6 34 56 78 90',
    address: 'Casablanca, Maroc',
    position: 'Monteuse',
    department_id: 3,
    department_name: 'Post-Production',
    salary: 38000,
    hire_date: '2023-02-10',
    status: 'active',
    created_at: '2023-02-10',
    updated_at: '2023-02-10',
    contract_type: 'CDI',
    contract_start_date: '2023-02-10',
    contract_status: 'active',
    active_projects: 2,
  },
  {
    id: 4,
    first_name: 'David',
    last_name: 'Chen',
    email: 'david.chen@nomedia.ma',
    phone: '+212 6 45 67 89 01',
    address: 'Casablanca, Maroc',
    position: 'Producteur',
    department_id: 4,
    department_name: 'Direction',
    salary: 55000,
    hire_date: '2022-11-05',
    status: 'active',
    created_at: '2022-11-05',
    updated_at: '2022-11-05',
    contract_type: 'CDI',
    contract_start_date: '2022-11-05',
    contract_status: 'active',
    active_projects: 2,
  },
];

export const mockProjects: Project[] = [
  {
    id: 1,
    name: 'Spot TV - Luxury Brand',
    client_name: 'Maison Deluxe',
    description: 'Production d\'un spot télévisé de 30 secondes pour une marque de luxe',
    status: 'production',
    priority: 'high',
    budget: 85000,
    spent: 55250,
    start_date: '2024-01-10',
    deadline: '2024-02-15',
    progress: 65,
    project_type: 'publicite',
    deliverables: ['Spot TV 30s', 'Version web', 'Making-of'],
    notes: 'Tournage en studio et en extérieur',
    client_contact_name: 'Sophie Dubois',
    client_contact_email: 'sophie@maison-deluxe.com',
    client_contact_phone: '+212 5 22 33 44 55',
    created_at: '2024-01-01',
    updated_at: '2024-01-10',
    team_member_count: 3,
    contracts_compliance: 67,
    team_members: [
      { employee_id: 1, employee_name: 'Alice Martin', role: 'Réalisatrice', start_date: '2024-01-10', status: 'active', contract_status: 'verified' },
      { employee_id: 2, employee_name: 'Bob Dupont', role: 'Cameraman', start_date: '2024-01-10', status: 'active', contract_status: 'uploaded' },
      { employee_id: 3, employee_name: 'Carol Leroy', role: 'Monteuse', start_date: '2024-01-15', status: 'active', contract_status: 'pending' },
    ],
  },
  {
    id: 2,
    name: 'Documentaire Corporate',
    client_name: 'TechCorp',
    description: 'Documentaire de 15 minutes sur l\'histoire et les valeurs de l\'entreprise',
    status: 'post_production',
    priority: 'medium',
    budget: 45000,
    spent: 38000,
    start_date: '2023-12-01',
    deadline: '2024-01-30',
    progress: 80,
    project_type: 'documentaire',
    deliverables: ['Documentaire 15min', 'Trailer 2min'],
    notes: 'Interviews avec les dirigeants et employés',
    client_contact_name: 'Jean Techno',
    client_contact_email: 'jean@techcorp.ma',
    client_contact_phone: '+212 5 22 11 22 33',
    created_at: '2023-11-15',
    updated_at: '2023-12-01',
    team_member_count: 2,
    contracts_compliance: 100,
    team_members: [
      { employee_id: 4, employee_name: 'David Chen', role: 'Réalisateur', start_date: '2023-12-01', status: 'active', contract_status: 'verified' },
      { employee_id: 3, employee_name: 'Carol Leroy', role: 'Monteuse', start_date: '2023-12-05', status: 'active', contract_status: 'verified' },
    ],
  },
  {
    id: 3,
    name: 'Campagne Publicitaire',
    client_name: 'FashionHouse',
    description: 'Série de 5 vidéos pour campagne publicitaire multi-canaux',
    status: 'pre_production',
    priority: 'high',
    budget: 120000,
    spent: 12000,
    start_date: '2024-01-20',
    deadline: '2024-03-10',
    progress: 25,
    project_type: 'publicite',
    deliverables: ['5 vidéos produits', 'Adaptation réseaux sociaux', 'Assets photos'],
    notes: 'Campagne automne-hiver 2024',
    client_contact_name: 'Marie Fashion',
    client_contact_email: 'marie@fashionhouse.ma',
    client_contact_phone: '+212 5 22 44 55 66',
    created_at: '2024-01-01',
    updated_at: '2024-01-20',
    team_member_count: 4,
    contracts_compliance: 50,
    team_members: [
      { employee_id: 1, employee_name: 'Alice Martin', role: 'Directrice Créative', start_date: '2024-01-20', status: 'active', contract_status: 'verified' },
      { employee_id: 4, employee_name: 'David Chen', role: 'Producteur', start_date: '2024-01-20', status: 'active', contract_status: 'uploaded' },
      { employee_id: 2, employee_name: 'Bob Dupont', role: 'Cameraman', start_date: '2024-01-25', status: 'active', contract_status: 'pending' },
    ],
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 1,
    invoiceNumber: "NOM-2024-001",
    client: "STE NEW GENERATION PICTURES",
    clientIce: "000515592000068",
    project: "DOUBLAGE MINI SERIE ATTAR",
    projectId: 1,
    amount: 60000.0,
    taxAmount: 12000.0,
    totalAmount: 72000.0,
    issueDate: "2024-01-06",
    dueDate: "2024-02-06",
    status: "paid",
    items: [
      {
        id: 1,
        description: "DOUBLAGE MINI SERIE ATTAR - Version originale : tachelhit - Versions doublées : Tarifit/ tamazight",
        unitPrice: 25000.0,
        quantity: 2,
        total: 50000.0,
      },
      {
        id: 2,
        description: "Post-production et montage",
        unitPrice: 10000.0,
        quantity: 1,
        total: 10000.0,
      },
    ],
    teamMembers: ["Mohammed Alami", "Fatima Zahra", "Ahmed Benali"],
    profitMargin: 35,
    estimatedCosts: 39000,
    assignedEmployees: [
      {
        employee_id: 1,
        employee_name: "Alice Martin",
        position: "Réalisatrice",
        department: "Production",
        role_in_project: "Responsable Doublage",
        hourly_rate: 250,
        hours_allocated: 80,
        cost_allocation: 20000,
        base_salary: 18000,
        overtime_hours: 10,
        overtime_rate: 375, // 1.5x hourly rate
        overtime_payment: 3750,
        bonus_amount: 2000,
        bonus_reason: "Excellente qualité du doublage",
        expense_reimbursements: 500,
        total_payment: 24250,
        payment_date: "2024-02-10",
        payment_status: 'paid',
        payment_method: "Virement bancaire",
        bank_details: "BMCE Bank - 007 123456789",
        taxes_withheld: 4850,
        net_payment: 19400,
        contract_type: "CDI",
        performance_bonus: 1500,
        project_completion_bonus: 1000,
        travel_allowance: 300,
        equipment_allowance: 200,
      },
      {
        employee_id: 3,
        employee_name: "Carol Leroy",
        position: "Monteuse",
        department: "Post-Production",
        role_in_project: "Mixage Audio",
        hourly_rate: 180,
        hours_allocated: 60,
        cost_allocation: 10800,
        base_salary: 10800,
        overtime_hours: 5,
        overtime_rate: 270,
        overtime_payment: 1350,
        bonus_amount: 800,
        bonus_reason: "Respect des délais serrés",
        expense_reimbursements: 200,
        total_payment: 13150,
        payment_date: "2024-02-10",
        payment_status: 'paid',
        payment_method: "Virement bancaire",
        bank_details: "Attijariwafa Bank - 004 987654321",
        taxes_withheld: 2630,
        net_payment: 10520,
        contract_type: "CDI",
        performance_bonus: 500,
        project_completion_bonus: 300,
        travel_allowance: 0,
        equipment_allowance: 100,
      },
    ],
    created_at: "2024-01-06T00:00:00Z",
    updated_at: "2024-01-06T00:00:00Z",
  },
  {
    id: 2,
    invoiceNumber: "NOM-2024-002",
    client: "TechCorp Solutions",
    clientIce: "000515592000069",
    project: "Documentaire Corporate",
    projectId: 2,
    amount: 450000.0,
    taxAmount: 90000.0,
    totalAmount: 540000.0,
    issueDate: "2024-01-31",
    dueDate: "2024-03-01",
    status: "pending",
    items: [
      {
        id: 3,
        description: "Production documentaire corporate 15 minutes",
        unitPrice: 300000.0,
        quantity: 1,
        total: 300000.0,
      },
      {
        id: 4,
        description: "Post-production et montage",
        unitPrice: 150000.0,
        quantity: 1,
        total: 150000.0,
      },
    ],
    teamMembers: ["Youssef Benali", "Aicha Lamrani", "Omar Tazi", "Nadia Khoury"],
    profitMargin: 42,
    estimatedCosts: 261000,
    assignedEmployees: [
      {
        employee_id: 4,
        employee_name: "David Chen",
        position: "Producteur",
        department: "Direction",
        role_in_project: "Directeur Artistique",
        hourly_rate: 400,
        hours_allocated: 200,
        cost_allocation: 80000,
        base_salary: 75000,
        overtime_hours: 15,
        overtime_rate: 600,
        overtime_payment: 9000,
        bonus_amount: 5000,
        bonus_reason: "Direction exceptionnelle du projet",
        expense_reimbursements: 1200,
        total_payment: 90200,
        payment_date: "2024-03-05",
        payment_status: 'pending',
        payment_method: "Virement bancaire",
        bank_details: "BMCI - 011 456789123",
        taxes_withheld: 18040,
        net_payment: 72160,
        contract_type: "CDI",
        performance_bonus: 3000,
        project_completion_bonus: 2500,
        travel_allowance: 800,
        equipment_allowance: 400,
      },
      {
        employee_id: 3,
        employee_name: "Carol Leroy",
        position: "Monteuse",
        department: "Post-Production",
        role_in_project: "Chef Opérateur",
        hourly_rate: 300,
        hours_allocated: 150,
        cost_allocation: 45000,
        base_salary: 42000,
        overtime_hours: 20,
        overtime_rate: 450,
        overtime_payment: 9000,
        bonus_amount: 3000,
        bonus_reason: "Qualité technique excellente",
        expense_reimbursements: 600,
        total_payment: 54600,
        payment_date: "2024-03-05",
        payment_status: 'pending',
        payment_method: "Virement bancaire",
        bank_details: "Attijariwafa Bank - 004 987654321",
        taxes_withheld: 10920,
        net_payment: 43680,
        contract_type: "CDI",
        performance_bonus: 2000,
        project_completion_bonus: 1500,
        travel_allowance: 200,
        equipment_allowance: 300,
      },
    ],
    created_at: "2024-01-31T00:00:00Z",
    updated_at: "2024-01-31T00:00:00Z",
  },
  {
    id: 3,
    invoiceNumber: "NOM-2024-003",
    client: "Maison Deluxe",
    clientIce: "000515592000070",
    project: "Spot TV - Luxury Brand",
    projectId: 3,
    amount: 850000.0,
    taxAmount: 170000.0,
    totalAmount: 1020000.0,
    issueDate: "2024-02-15",
    dueDate: "2024-03-15",
    status: "overdue",
    items: [
      {
        id: 5,
        description: "Production spot TV 30 secondes",
        unitPrice: 500000.0,
        quantity: 1,
        total: 500000.0,
      },
      {
        id: 6,
        description: "Location matériel professionnel",
        unitPrice: 200000.0,
        quantity: 1,
        total: 200000.0,
      },
      {
        id: 7,
        description: "Post-production et étalonnage",
        unitPrice: 150000.0,
        quantity: 1,
        total: 150000.0,
      },
    ],
    teamMembers: ["Hassan Idrissi", "Laila Moussaoui", "Rachid Benjelloun", "Samira El Fassi", "Karim Ouali"],
    profitMargin: 28,
    estimatedCosts: 612000,
    assignedEmployees: [
      {
        employee_id: 1,
        employee_name: "Alice Martin",
        position: "Réalisatrice",
        department: "Production",
        role_in_project: "Producer Exécutif",
        hourly_rate: 500,
        hours_allocated: 300,
        cost_allocation: 150000,
        base_salary: 140000,
        overtime_hours: 30,
        overtime_rate: 750,
        overtime_payment: 22500,
        bonus_amount: 8000,
        bonus_reason: "Leadership et gestion d'équipe exceptionnels",
        expense_reimbursements: 2000,
        total_payment: 172500,
        payment_date: "2024-03-20",
        payment_status: 'pending',
        payment_method: "Virement bancaire",
        bank_details: "BMCE Bank - 007 123456789",
        taxes_withheld: 34500,
        net_payment: 138000,
        contract_type: "CDI",
        performance_bonus: 5000,
        project_completion_bonus: 4000,
        travel_allowance: 1500,
        equipment_allowance: 1000,
      },
      {
        employee_id: 2,
        employee_name: "Bob Dupont",
        position: "Cameraman",
        department: "Technique",
        role_in_project: "Direction Technique",
        hourly_rate: 350,
        hours_allocated: 200,
        cost_allocation: 70000,
        base_salary: 65000,
        overtime_hours: 25,
        overtime_rate: 525,
        overtime_payment: 13125,
        bonus_amount: 4000,
        bonus_reason: "Innovation technique et qualité d'image",
        expense_reimbursements: 800,
        total_payment: 82925,
        payment_date: "2024-03-20",
        payment_status: 'cancelled',
        payment_method: "Virement bancaire",
        bank_details: "CIH Bank - 006 741852963",
        taxes_withheld: 16585,
        net_payment: 66340,
        contract_type: "CDD",
        performance_bonus: 2500,
        project_completion_bonus: 2000,
        travel_allowance: 600,
        equipment_allowance: 800,
      },
    ],
    created_at: "2024-02-15T00:00:00Z",
    updated_at: "2024-02-15T00:00:00Z",
  },
];

// Mock API responses
export const getMockProjects = () => Promise.resolve({ success: true, data: mockProjects });
export const getMockEmployees = () => Promise.resolve({ success: true, data: mockEmployees });
export const getMockDepartments = () => Promise.resolve({ success: true, data: mockDepartments });
export const getMockContractTypes = () => Promise.resolve({ success: true, data: mockContractTypes });
export const getMockInvoices = () => Promise.resolve({ success: true, data: mockInvoices });

export const getMockEmployeeStats = () => Promise.resolve({
  success: true,
  data: {
    general: {
      total_employees: mockEmployees.length,
      active_employees: mockEmployees.filter(e => e.status === 'active').length,
      inactive_employees: mockEmployees.filter(e => e.status === 'inactive').length,
      on_leave_employees: mockEmployees.filter(e => e.status === 'on_leave').length,
      total_active_payroll: mockEmployees.filter(e => e.status === 'active').reduce((sum, e) => sum + e.salary, 0),
      total_departments: mockDepartments.length,
    },
    contractTypes: mockContractTypes.map(ct => ({ contract_type: ct.name, count: Math.floor(Math.random() * 5) + 1 }))
  }
});

export const getMockProjectStats = () => Promise.resolve({
  success: true,
  data: {
    general: {
      total_projects: mockProjects.length,
      pre_production_projects: mockProjects.filter(p => p.status === 'pre_production').length,
      production_projects: mockProjects.filter(p => p.status === 'production').length,
      post_production_projects: mockProjects.filter(p => p.status === 'post_production').length,
      completed_projects: mockProjects.filter(p => p.status === 'completed').length,
      total_budget: mockProjects.reduce((sum, p) => sum + p.budget, 0),
      total_spent: mockProjects.reduce((sum, p) => sum + p.spent, 0),
      average_progress: mockProjects.reduce((sum, p) => sum + p.progress, 0) / mockProjects.length,
    },
    priorities: [
      { priority: 'high', count: mockProjects.filter(p => p.priority === 'high').length },
      { priority: 'medium', count: mockProjects.filter(p => p.priority === 'medium').length },
      { priority: 'low', count: mockProjects.filter(p => p.priority === 'low').length },
    ]
  }
});

export const getMockInvoiceStats = () => Promise.resolve({
  success: true,
  data: {
    total_invoices: mockInvoices.length,
    draft_invoices: mockInvoices.filter(i => i.status === 'draft').length,
    pending_invoices: mockInvoices.filter(i => i.status === 'pending').length,
    paid_invoices: mockInvoices.filter(i => i.status === 'paid').length,
    overdue_invoices: mockInvoices.filter(i => i.status === 'overdue').length,
    total_revenue: mockInvoices.filter(i => i.status === 'paid').reduce((sum, i) => sum + i.totalAmount, 0),
    total_pending_amount: mockInvoices.filter(i => i.status === 'pending' || i.status === 'overdue').reduce((sum, i) => sum + i.totalAmount, 0),
    average_invoice_value: mockInvoices.reduce((sum, i) => sum + i.totalAmount, 0) / mockInvoices.length,
    total_profit_margin: mockInvoices.filter(i => i.profitMargin).reduce((sum, i) => sum + (i.profitMargin || 0), 0) / mockInvoices.filter(i => i.profitMargin).length,
  }
});

export const getMockDashboardStats = () => Promise.resolve({
  success: true,
  data: {
    projects: {
      total_projects: mockProjects.length,
      pre_production_projects: mockProjects.filter(p => p.status === 'pre_production').length,
      production_projects: mockProjects.filter(p => p.status === 'production').length,
      post_production_projects: mockProjects.filter(p => p.status === 'post_production').length,
      completed_projects: mockProjects.filter(p => p.status === 'completed').length,
      total_budget: mockProjects.reduce((sum, p) => sum + p.budget, 0),
      total_spent: mockProjects.reduce((sum, p) => sum + p.spent, 0),
      average_progress: mockProjects.reduce((sum, p) => sum + p.progress, 0) / mockProjects.length,
    },
    employees: {
      total_employees: mockEmployees.length,
      active_employees: mockEmployees.filter(e => e.status === 'active').length,
      inactive_employees: mockEmployees.filter(e => e.status === 'inactive').length,
      on_leave_employees: mockEmployees.filter(e => e.status === 'on_leave').length,
      total_active_payroll: mockEmployees.filter(e => e.status === 'active').reduce((sum, e) => sum + e.salary, 0),
      total_departments: mockDepartments.length,
    },
    invoices: {
      total_invoices: mockInvoices.length,
      draft_invoices: mockInvoices.filter(i => i.status === 'draft').length,
      pending_invoices: mockInvoices.filter(i => i.status === 'pending').length,
      paid_invoices: mockInvoices.filter(i => i.status === 'paid').length,
      overdue_invoices: mockInvoices.filter(i => i.status === 'overdue').length,
      total_revenue: mockInvoices.filter(i => i.status === 'paid').reduce((sum, i) => sum + i.totalAmount, 0),
      total_pending_amount: mockInvoices.filter(i => i.status === 'pending' || i.status === 'overdue').reduce((sum, i) => sum + i.totalAmount, 0),
    },
    expenses: {
      total_expenses: 0,
      pending_expenses: 0,
      approved_expenses: 0,
      total_amount: 0,
    },
    recentActivity: [
      {
        id: 1,
        type: 'project',
        title: 'Spot TV - Luxury Brand',
        description: 'Projet en production, 65% terminé',
        timestamp: '2024-01-10',
        first_name: 'Maison',
        last_name: 'Deluxe',
        position: 'Client',
        status: 'production'
      },
      {
        id: 2,
        type: 'user',
        title: 'David Chen',
        description: 'Nouveau producteur ajouté à l\'équipe',
        timestamp: '2022-11-05',
        first_name: 'David',
        last_name: 'Chen',
        position: 'Producteur',
        status: 'active'
      },
      {
        id: 3,
        type: 'project',
        title: 'Documentaire Corporate',
        description: 'Post-production en cours, 80% terminé',
        timestamp: '2023-12-01',
        first_name: 'TechCorp',
        last_name: '',
        position: 'Client',
        status: 'post_production'
      }
    ]
  }
});
